### ISSUE TITLE
Issue enumerating folders

### ISSUE THREAD

**Issue by deep0d0** [PrivacyDevel/OneDrive-MassDL-Cli#2]
Traceback (most recent call last):
  File "/Users/deep0d0/Desktop/./down.py", line 95, in <module>
    download_onedrive_folder(data['authKey'], data['id'], data['cid'], 'downloads')
  File "/Users/deep0d0/Desktop/./down.py", line 58, in download_onedrive_folder
    download_onedrive_folder(data['authKey'], child['id'], child['resourcePartitionCid'], path)
  File "/Users/deep0d0/Desktop/./down.py", line 58, in download_onedrive_folder
    download_onedrive_folder(data['authKey'], child['id'], child['resourcePartitionCid'], path)
  File "/Users/deep0d0/Desktop/./down.py", line 58, in download_onedrive_folder
    download_onedrive_folder(data['authKey'], child['id'], child['resourcePartitionCid'], path)
  [Previous line repeated 1 more time]
  File "/Users/deep0d0/Desktop/./down.py", line 70, in download_onedrive_folder
    raise Exception('Unknown itemType ' + str(item['itemType']))
Exception: Unknown itemType 32

**Comment by Keil-Simion** [comment]
Hello, I've met the same issue as you
It seems some file have special 'itemtype', not always 1, as line 60 assumed
In the case of wave file, 'itemtype' is 9, and it should work fine
![image](https://github.com/user-attachments/assets/b50e3e7d-7390-449d-b5f3-914393256539)
